language: php
 
branches:
  only:
    - master
    - dev
 
cache:
  directories:
    - $HOME/.composer/cache
 
matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_TRAVISCI=phpcs
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 5.5
      env: WP_VERSION=5.1
    - php: 5.4
      env: WP_VERSION=5.1
 
before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
 
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0
 
install:
  # Install our Composer dependencies
  - composer install --prefer-dist --no-interaction
 
script:
  - |
    # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      ./vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/php-compatibility
      ./vendor/bin/phpcs
    fi